---
language: bash


sudo: false

install:
  - nvm install 6
  - nvm use 6
  - npm install -g elm@0.17.1 elm-test@0.17.3
  - elm package install -y

script:
  - bin/fetch-configlet
  - bin/configlet .
  - bin/build.sh
